# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'abcca6e6-4090-4efa-8a6d-ea99d8de2642'
  imageRepository: 'alexandrusandudsandercoualexandruassignmentmaketha'
  containerRegistry: 'ds2022energyfacilityandercoualexandru.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/spring-demo/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: CodeCoverage
    displayName: Code Coverage
    pool:
      name: local
    steps:
    - task: Maven@3
      displayName: Build and push an image to container registry
      inputs:
        mavenPomFile: "spring-demo/pom.xml"
        codeCoverageToolOption: JaCoCo
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
