# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '9e1c69ca-abee-4513-bbff-0fc05a86e9a6'
  imageRepository: 'hopedieslast'
  containerRegistry: 'ds2022energyfacilityandercoualexandru.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/spring-demo/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: CodeCovrage
    displayName: Code Covrage
    pool:
      name: local
    steps:
    - task: Maven@3
      displayName: Build and push an image to container registry
      inputs:
        mavenPomFile: "spring-demo/pom.xml"
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
