# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'f4002776-32ac-4057-8a44-b126204ac36c'
  imageRepository: 'notthateasy'
  containerRegistry: 'ds2022energyfacilityandercoualexandru.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/spring-demo/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: CodeCoverage
    displayName: Code Coverage
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Maqven@3
      displayName: Build and push an image to container registry
      inputs:
        mavenPomFile: "spring-demo/pom.xml"
        codeCoverageToolOptions: JaCoCo
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
