# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '36b19ae4-3e06-4879-8585-9d31dd9f9052'
  imageRepository: 'hailwindows'
  containerRegistry: 'ds2022energyfacilityandercoualexandru.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/spring-demo/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: CodeCoverage
    displayName:  Code Covrage
    pool:
      local
    steps:
    - task: Maven@3
      displayName: Build and push an image to container registry
      inputs:
        mavenPomFile: "spring-demo/pom.xml"
        publishJUnitResults: true
        testResultsFiles: "**/surfire-reports/TESTS-*.xml"
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        codeCoverageToolOption: JaCoCo
        tags: |
          $(tag)
